### ISSUE TITLE
Calling AddMulti for a single entity instead of Add

### ISSUE THREAD

**Issue by johngb** [qedus/nds#50]
I'm occasionally getting a warning of: `nds:lockMemcache AddMulti memcache: item not stored`

While I'm fine with the occasional Memcache error being thrown, this is happening when saving a single entity.  I'm not sure why nds is calling AddMulti for a single entity instead of Add.

**Comment by jongillham** [comment]
Is it happening consistently when saving a single entity or is that occasional as well?

The reason `memcache.AddMulti` is called instead of `memcache.Add` when one entity is being stored is because the functions make the same backend RPC call so there is no performance advantage by using `Add` when we are storing only one entity. Therefore the `nds` code is a bit cleaner not having an `if len(item) == 1 { memcache.Add } else { memcache.AddMulti }` statement:

[`google.golang.org/appengine/memcache.Add`](https://github.com/golang/appengine/blob/08a149cfaee099e6ce4be01c0113a78c85ee1dee/memcache/memcache.go#L329)
[`google.golang.org/appengine/memcache.AddMulti`](https://github.com/golang/appengine/blob/08a149cfaee099e6ce4be01c0113a78c85ee1dee/memcache/memcache.go#L335)

**Comment by johngb** [comment]
No, it's not happening consistently.  I think that the error is a general Memcache error that is thrown by AppEngine depending on load etc, so I'm not worried about it.  The error being a AddMulti error is what concerned me as a possible bug, but your explanation makes a lot of sense, thanks.
