### ISSUE TITLE
Gracefully handle memcache quota limits

### ISSUE THREAD

**Issue by derekperkins** [qedus/nds#57]
We started randomly seeing memcache quota errors that ended up failing our Put operations. We're paying customers, so I'm not sure why those started showing, but it seems reasonable to me to have `nds` bypass memcache and go directly to datastore on this error. What do you think?

![image](https://user-images.githubusercontent.com/3588778/32286807-4c0a671e-bef4-11e7-85cc-486a1a87230d.png)

**Comment by jongillham** [comment]
Currently `nds` will only fail a datastore operation when a memcache fail can potentially cause data inconsistency. If we take the situation where the memcache is working and `nds` saves something in it and it then stops working because of over quota limits, for example. If you try to `Put` to the datastore `nds` needs to ensure that the memcache is also deleted/updated. As it can't contact memcache it fails the entire `Put` operation for data consistency reasons. A subsequent `Get` may potentially return stale results if the memcache starts working again and the `Get` pulls the stale memcache value.

I had thought about using the [capability](https://godoc.org/google.golang.org/appengine/capability) API but that causes an extra RPC call and you still have the same issues as above.

If you don't require datastore consistency it could be simpler to role your own "try to get from memcache, if that fails then get from datastore".

**Comment by derekperkins** [comment]
@jongillham makes sense. Thanks for the feedback.
