### ISSUE TITLE
Make PutMulti and DeleteMulti execute concurrent requests when over API limit.

### ISSUE THREAD

**Issue by qedus** [qedus/nds#6]
Needs the same functionality as GetMulti.

**Comment by derekperkins** [comment]
Would this check both the number of records and the overall record size?

**Comment by mzimmerman** [comment]
I wrote this feature for goon, it's not as trivial as it sounds there's
lots of gotcha, particularly how you return on partial success.

**Comment by jongillham** [comment]
@derekperkins I am not quite sure what you mean. `appengine/datastore` only allows you to `GetMulti` a maximum of 1000 entities in one go. `PutMulti` and `DeleteMulti only allow 500 entities. With `nds.GetMulti` it breaks the entities up into chunks of 1000 or less and then executes concurrently as many calls to `datastore.GetMulti` as necessary to retrieve all the entities. This doesn't currently happen with `nds.PutMulti` and `nds.DeleteMulti` but I would like to add code to make it happen.

In practical terms though if I were to try to `nds.GetMulti` 5000 entities, each 1Kb big then I would need to set my context timeout to 30 seconds from the default 5 seconds and even then would probably get timeout errors.

@mzimmerman is right about it being non trivial to implement. If he looks closely, he might see how similar my implementation is to his. Thanks for the help Matthew. :stuck_out_tongue_winking_eye: I originally wrote my code with channels and realised Goon's looked much nicer.

**Comment by derekperkins** [comment]
@mzimmerman I wasn't trying to make it sound trivial. We've looked at implementing this for a while now, but haven't precisely because it is complex.

@jongillham There are more reasons to chunk it up than just the record count. We have also run into issues where the total size of the `PutMulti` causes an error. I don't know if that is because it is the 10 MB transactional limit mentioned here https://cloud.google.com/appengine/docs/go/datastore/#Go_Quotas_and_limits or some undocumented limit.

We refer to that error internally as `Too big for missiles, switching to guns`, because we sometimes have to not use a `PutMulti` and instead do a lot of concurrent `Put`s. There's for sure some optimal middle ground there, but we haven't found it yet.

**Comment by jongillham** [comment]
@derekperkins I understand now. I've not run into that limit yet. I have a feeling that the maximum size an RPC response can be is 32Mb. So you would want to automatically chunk you're Gets/Puts/Deletes if the size is > 10/32Mb or number of entities > 1000. That seems useful. It would almost certainly have to use some reflection to follow down struct members counting the size of each member.

**Comment by derekperkins** [comment]
I just ran into this over the weekend and got verification that there is a 1 MB limit for a PutMulti.
"There's a per-API call limit of 1 MB for almost every API call, including datastore.*." - David Symonds
https://groups.google.com/forum/#!topic/google-appengine-go/kzSVWIwIbP0

**Comment by kidoman** [comment]
Ran into this just now. Possible to prioritize this? Or do you want a PR?

**Comment by jongillham** [comment]
Hi @kidoman I'm happy to add the feature. I just need to do a bit of research as @mzimmerman is right. It isn't as trivial as it sounds due to the possibility of partial failure.

@mzimmerman how did you tackle the problem with [Goon](https://github.com/mjibson/goon) if one `datastore.PutMulti` succeeds and another one fails for a single call of `nds.PutMulti`? I believe that `datastore.PutMulti` can also have partial failure? If that's the case then I suppose I would just return and `appengine.MultiError` from my `nds.PutMulti` and mark all the errors associated with the failed `datastore.PutMulti` as non nil. Does that sound reasonable?

**Comment by mzimmerman** [comment]
Yes, that's exactly right, a MultiError.
https://github.com/mjibson/goon/blob/master/goon.go#L220

See https://github.com/mjibson/goon/pull/20 for the discussion around the
design decisions

**Comment by jongillham** [comment]
@mzimmerman thanks for the input.

@kidoman I've released the changes to the [concurrent](https://github.com/qedus/nds/tree/concurrent) branch. Please let me know how you get on and I'll merge it to master in a few days if everything is OK.

**Comment by kidoman** [comment]
@jongillham I have looked the code and left a few comments.

**Comment by jongillham** [comment]
@kidoman here's the next instalment b240b981d4e3c878d920f9fe3f615a3101d4d549 with your suggestions. Thanks for spotting the potentially disastrous race condition bug!

**Comment by kidoman** [comment]
Looking forward to the merge!

**Comment by jongillham** [comment]
Commit 705d16867a3bae722a74dffbed311996b92f432d adds this functionality.

**Comment by kidoman** [comment]
Danke!
