### ISSUE TITLE
Change module versioning from git branches to subdirectories.

### ISSUE THREAD

**Issue by jongillham** [qedus/nds#73]
I propose we use the github.com/qedus/nds/v2 directory to contain version 2 code instead of the v2 branch.

@someone1 I'm interested to hear your thoughts.

**Comment by someone1** [comment]
Over the last year or so, most projects I've been using/following seem to have switched over to the branch approach (though in varying ways), but I do understand the subdirectory approach is the most backwards compatible. This may no longer be an issue since all supported versions of Go support modules, even with some support being backported all the way to 1.9.7.

I have some experience managing repos with submodules - it doesn't work as I would have hoped but as long as you're aware of the nuances its not any more/less work than the dedicated branch approach. Things like `go test ./...` will skip all submodules so you need to update CI scripts accordingly and although it was more of a problem previously, IDE's seem to trip over themselves figuring out modules vs submodule deps and bringing one set of deps into the other erroneously.

I think at this point is just a preference on how you want to organize the code between versions. I find myself migrating away from AppEngine and using this library on Cloud Run or Cloud Functions - so any arguments for the older toolchain or Gen1 AppEngine support don't apply much to me anymore. 

I'd be happy to continue help supporting either method and defer to whichever preference you have!

**Comment by jongillham** [comment]
Thanks for the input @someone1. The reason I suggested this was because [Go Modules: v2 and Beyond](https://blog.golang.org/v2-go-modules) says using directories is the recommended strategy.

Why don't we just leave it as it is and raise this issue again if versioning by branch ever becomes deprecated or tools become less compatible.
